#Makefile

CFLAGS = -c -ansi -g

all:january2019

january2019: january2019.o
	gcc -o january2019 january2019.o

january2019.o: january2019.c
	gcc $(FLAGS) january2019.c

clean:
	rm -f *.o january2019
